image: docker:19.03.12

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  tags:
    - did-runner
  script:
    - apt update
    - apt install curl
    - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - mkdir -p "$MOUNT_POINT"
    - sh ./docker/run-stack.sh