image: docker:19.03.12

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  tags:
    - did-runner
  environment:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - apk add docker-compose
    - echo "$MOUNT_POINT"
    - cd docker && sh ./run-stack.sh