image: docker:19.03.12

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:19.03.12-dind

build:
  stage: build
  tags:
    - did-runner
  script:
    - apk add docker-compose
    - echo "$MOUNT_POINT"
    - cd docker && sh ./run-stack.sh