image: docker:19.03.12

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:19.03.12-dind

before_script:
  - chmod -R 777 $MOUNT_POINT/tezos-app-project
  - ls -al $MOUNT_POINT/tezos-app-project
  - echo "Mount Point $MOUNT_POINT"

build:
  stage: build
  tags:
    - did-runner
  script:
    - apk add docker-compose
    - echo "$MOUNT_POINT"
    - cd docker && sh ./run-stack.sh