image: docker:19.03.12

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  tags:
    - did-runner
  script:
    - apk add docker-compose
    - mkdir -p "$MOUNT_POINT"
    - cd docker && sh ./run-stack.sh