version: '3'

services:

  sandbox:
    container_name: tzkt-sandbox
    image: tqtezos/flextesa:20210602
    volumes:
      - ../tezos-app-project/src/contract/deployment.sh:/opt/contract/deployment.sh
      - ../tezos-app-project/src/contract/TZMINT.py:/opt/contract/TZMINT.py
      - ../tezos-app-project/src/contract/TZMINT.tz:/opt/contract/TZMINT.tz
      - ./scripts/deploy.sh:/opt/contract/deploy.sh
    command: flobox start
    ports:
      - 0.0.0.0:20000:20000

  db:
    container_name: tzkt-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 0.0.0.0:5432:5432

  api:
    container_name: tzkt-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - db
    environment:
      - TZKT_API_KESTREL__ENDPOINTS__HTTP__URL=http://0.0.0.0:5000
    expose:
      - 5000
    ports:
      - 0.0.0.0:5000:5000

  sync:
    container_name: tzkt-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    depends_on:
      - db
    entrypoint: /bin/bash -c 'sed -i "s/https:\/\/mainnet-tezos.giganode.io/http:\/\/tzkt-sandbox:20000/g" /app/appsettings.json && dotnet Tzkt.Sync.dll'

volumes:
  postgres: